---
title: "A JSDM with zero-inflation to increase the ecological relevance of analyses of species distribution data."
author: "AAA"
format: html
editor: visual
---

# Useful libraries & functions

PLNmodels version should be 1.2.2 or higher.

```{r, loading libraries}
library(PLNmodels)
library(Metrics)
library(pheatmap)
library(tidyverse)
library(FactoMineR)
library(factoextra)
library(viridisLite)
```

# Loading & formatting data

## Data loading

```{r data-loading}
load("data/NORTHERN_RANGE_DATASET_COUNTS.Rdata")
NR_COUNTS <- NORTHERN_RANGE_DATASET_COUNTS %>% as_tibble()
NR_COUNTS <- NR_COUNTS[, -21]

load("data/NORTHERN_RANGE_DATASET_COVARIATES.Rdata")
NR_COVARIATES <- 
  NORTHERN_RANGE_DATASET_COVARIATES %>% as_tibble() %>% 
  rename(latitude = LATITUDE, 
         longitude = LONGITUDE, 
         long_lat = LONGLAT,
         coarse_gravel = coarse.gravel, # We do not include geographical coordinates here
         fine_gravel = fine.gravel, 
         leaf_litter = leaf.litter,
         time_step = TimeStep, year = YEAR, month = MONTH, 
         stream = STREAM, 
         disturbance = DISTURBANCE, # human activity / binary categorical variable
         altitude = ALTITUDE, 
         season = SEASON) %>% 
  mutate(
    # season = case_match(time_step,
    #   c(1, 5,  9, 13, 17) ~ "dry_start",
    #   c(2, 6, 10, 14, 18) ~ "dry_end",
    #   c(3, 7, 11, 15, 19) ~ "wet_start",
    #   c(4, 8, 12, 16    ) ~ "wet_end"
    # ),
    season = as.character(season),
    year = as.character(year),
    disturbance = ifelse(disturbance == 1, "yes", "no")
  ) %>% 
  ## flow is not reliable
  ## time_step + month are redundant with season + year
  ## site is redudant with disturbance + stream
  ## long_lat is the 1st PCA axis of latitude + longitude
  dplyr::select(-latitude, -longitude, - long_lat, -site, -time_step,
                -month, -flow) %>% # we remove geographical coordinates
  relocate(altitude, width, depth, volume, garbage,
           conductivity, O2, pH, temperature, turbidity, # site features
           coarse_gravel, fine_gravel, leaf_litter, cobble, sand, silt, boulders, canopy, # soil
           season, year, # sampling time
           stream, disturbance # categorical: place + human activity
         )
# turbidity: ordinal variable indicating the level of turbidity
# season:-> dry-start/dry-end, wet-start/wet-end, (january-> may: dry)
quali_ind <- seq(ncol(NR_COVARIATES) - 3, ncol(NR_COVARIATES))

```

## Data visualization

```{r, data-visualization}
log_abundance <- log(1 + NR_COUNTS)
log_abundance_sorted <- log_abundance[order(NR_COVARIATES$stream), ]


color_palette  <- paletteer::paletteer_c("ggthemes::Orange-Gold", n = 30)
palette_colors <- paletteer::paletteer_c("ggthemes::Orange-Gold", n = 29)  # 29 instead of 30
color_palette <- c("white", palette_colors)
max_val <- max(log_abundance_sorted, na.rm = TRUE)

pheatmap(log_abundance_sorted,
         color = color_palette,
         cluster_rows = FALSE, cluster_cols = FALSE,
         annotation_row = data.frame(Stream = NR_COVARIATES$stream),
         show_rownames = FALSE)
```

## Covariates preparation (PCA)

```{r pca}
nb_pc <- ncol(NR_COVARIATES) - 4
NR_PCA <-
  NR_COVARIATES %>%
  PCA(quali.sup = quali_ind, ncp = nb_pc, scale.unit = TRUE, graph = FALSE)

NR_PCA_SCORES <- setNames(data.frame(NR_PCA$ind$coord), paste0("PC",1:nb_pc))
```

```{r data-formatting}
NR_DATA <- prepare_data(
  counts     = NR_COUNTS,
  covariates = cbind(NR_COVARIATES, NR_PCA_SCORES)
  )
```

# Running PLN-network

```{r pln_network_pc1_pc2}
model_PLN_pc1_pc2  <- PLNnetwork(Abundance ~ PC1 + PC2,  data = NR_DATA,
                         control = PLNnetwork_param(min_ratio = 0.05,
                                                    penalize_diagonal = FALSE))

model_PLN_pc1_pc2_StARS <- model_PLN_pc1_pc2$getBestModel("StARS", stability = 0.8)
# model_PLN_pc1_pc2_StARS <- model_PLN_pc1_pc2$getModel(0.2444352)

model_PLN_pc1_pc2_StARS$plot_network()

B_log_scale <- sign(model_PLN_pc1_pc2_StARS$model_par$B) * log1p(abs(model_PLN_pc1_pc2_StARS$model_par$B))
rownames(B_log_scale) <- c("Intercept", "PC1", "PC2")

pheatmap(B_log_scale,color = paletteer::paletteer_c("viridis::viridis", 30),
         cluster_rows = FALSE, cluster_cols = FALSE)
```

```{r pln_network_pc1_pc1_disturbance}
model_PLN_pc1_pc2_disturbance  <- PLNnetwork(Abundance ~ PC1 + PC2 + disturbance,  data = NR_DATA,
                         control = PLNnetwork_param(min_ratio = 0.05,
                                                    penalize_diagonal = FALSE))
model_PLN_pc1_pc2_disturbance_StARS <- model_PLN_pc1_pc2_disturbance$getBestModel("StARS", stability = 0.8)
# model_PLN_pc1_pc2_disturbance_StARS <- model_PLN_pc1_pc2_disturbance$getModel(0.2361045)

model_PLN_pc1_pc2_disturbance_StARS$plot_network()

B_log_scale <- sign(model_PLN_pc1_pc2_disturbance_StARS$model_par$B) * log1p(abs(model_PLN_pc1_pc2_disturbance_StARS$model_par$B))
rownames(B_log_scale) <- c("Intercept", "PC1", "PC2", "disturbance")
pheatmap(B_log_scale,
         color = paletteer::paletteer_c("viridis::viridis", 30),
         cluster_rows = FALSE, cluster_cols = FALSE)
```

```{r pln_network}
model_PLN  <- PLNnetwork(Abundance ~ PC1 + PC2 + stream + disturbance,  data = NR_DATA,
                         control = PLNnetwork_param(min_ratio = 0.05,
                                                    penalize_diagonal = FALSE))
model_PLN_StARS <- model_PLN$getBestModel("StARS", stability = 0.8)
# model_PLN_StARS <- model_PLN$getModel(0.06570186)

model_PLN_StARS$plot_network()

B_log_scale <- sign(model_PLN_StARS$model_par$B) * log1p(abs(model_PLN_StARS$model_par$B))
rownames(B_log_scale) <- c("Intercept", "PC1", "PC2", "stream_Caura", "stream_Lopinot",
                           "stream_LowerAripo", "stream_Maracas",   "stream_Quare",
                           "stream_Turure", "stream_UpperAripo", "disturbance")
pheatmap(B_log_scale,
         color = paletteer::paletteer_c("viridis::viridis", 30),
         cluster_rows = FALSE, cluster_cols = FALSE)
```

# Running ZIPLN-network

```{r zipln_network_pc1_pc2 }
model_ZIPLN_pc1_pc2   <- ZIPLNnetwork(Abundance ~ PC1 + PC2 | 1,  data = NR_DATA,
                         control = ZIPLNnetwork_param(min_ratio = 0.05,
                                                      penalize_diagonal = FALSE))
model_ZIPLN_pc1_pc2_StARS <- model_ZIPLN_pc1_pc2$getBestModel("StARS", stability = 0.8)
# model_ZIPLN_pc1_pc2_StARS <- model_ZIPLN_pc1_pc2$getModel(0.05578001)

model_ZIPLN_pc1_pc2_StARS$plot_network()

B_log_scale <- sign(model_ZIPLN_pc1_pc2_StARS$model_par$B) * log1p(abs(model_ZIPLN_pc1_pc2_StARS$model_par$B))
rownames(B_log_scale) <- c("Intercept", "PC1", "PC2")
pheatmap(B_log_scale,
         color = paletteer::paletteer_c("viridis::viridis", 30),
         cluster_rows = FALSE, cluster_cols = FALSE)

pheatmap(model_ZIPLN_pc1_pc2_StARS$model_par$Pi,
          color = paletteer::paletteer_c("viridis::cividis", 30),
          cluster_rows = FALSE, cluster_cols = FALSE)
```

```{r zipln_network_pc1_pc2_disturbance }
model_ZIPLN_pc1_pc2_disturbance   <- ZIPLNnetwork(Abundance ~ PC1 + PC2 + disturbance | 1,  data = NR_DATA,
                                                  control = ZIPLNnetwork_param(min_ratio = 0.05,
                                                      penalize_diagonal = FALSE))
model_ZIPLN_pc1_pc2_disturbance_StARS <- model_ZIPLN_pc1_pc2_disturbance$getBestModel("StARS", stability = 0.8)
# model_ZIPLN_pc1_pc2_disturbance_StARS <- model_ZIPLN_pc1_pc2_disturbance$getModel(0.04622685)


model_ZIPLN_pc1_pc2_disturbance_StARS$plot_network()

B_log_scale <- sign(model_ZIPLN_pc1_pc2_disturbance_StARS$model_par$B) * log1p(abs(model_ZIPLN_pc1_pc2_disturbance_StARS$model_par$B))
rownames(B_log_scale) <- c("Intercept", "PC1", "PC2", "disturbance")
pheatmap(B_log_scale,
         color = paletteer::paletteer_c("viridis::viridis", 30),
         cluster_rows = FALSE, cluster_cols = FALSE)

pheatmap(model_ZIPLN_pc1_pc2_disturbance_StARS$model_par$Pi,
         color = paletteer::paletteer_c("viridis::cividis", 30),
         cluster_rows = FALSE, cluster_cols = FALSE)
```

```{r zipln_network}
model_ZIPLN  <- ZIPLNnetwork(Abundance ~ PC1 + PC2 + disturbance | stream,  data = NR_DATA,
                         control = ZIPLNnetwork_param(min_ratio = 0.05,
                                                      penalize_diagonal = FALSE))
model_ZIPLN_StARS <- model_ZIPLN$getBestModel("StARS", stability = 0.8)
# model_ZIPLN_StARS <- model_ZIPLN$getModel(0.03317969)

model_ZIPLN_StARS$plot_network()

B_log_scale <- sign(model_ZIPLN_StARS$model_par$B) * log1p(abs(model_ZIPLN_StARS$model_par$B))
rownames(B_log_scale) <- c("Intercept", "PC1", "PC2", "disturbance")
pheatmap(B_log_scale,
         color = paletteer::paletteer_c("viridis::viridis", 30),
         cluster_rows = FALSE, cluster_cols = FALSE)

pheatmap(model_ZIPLN_pc1_pc2_disturbance_StARS$model_par$Pi,
         color = paletteer::paletteer_c("viridis::cividis", 30),
         cluster_rows = FALSE, cluster_cols = FALSE)
```

```{r}
pi_proba <- model_ZIPLN_StARS$model_par$Pi 
pi_proba_df <- as.data.frame(pi_proba)

STREAM <- NR_DATA$stream
# Assume M is a matrix and V is a vector of same length as nrow(M)

# Convert to data frame

pi_proba_df$STREAM <- STREAM

# Keep one row per unique value of V
pi_proba_unique <- pi_proba_df %>%
  group_by(STREAM) %>%
  slice(1) %>%
  ungroup()

# Extract matrix part
pi_proba_final <- as.matrix(select(pi_proba_unique, -STREAM))

# Set row names as the values of V
rownames(pi_proba_final) <- pi_proba_unique$V

# Plot the heatmap

pheatmap(pi_proba_final,
         color = rev(paletteer::paletteer_c("viridis::cividis", 30)),
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         show_rownames = TRUE)  # show V as row names


```

